### ISSUE TITLE
UnboundedLocalError After Setting Up automate.yml file through crosscompute cli 

### ISSUE THREAD

**Issue by kashfifahim** [crosscompute/crosscompute#52]
```
(cupdate) kashfifahim@Kashfis-Air ta2 % crosscompute
2022-02-23 12:35:41 INFO existing configuration not found; configuring new automation

automation name [Automation X]: TryAgain2
automation version [0.0.0]: 0.0.0
configuration path [automate.yml]: automate.yml
{'crosscompute': '0.9.1', 'name': 'TryAgain2', 'version': '0.0.0'}
save? yes or [no]: yes
2022-02-23 12:35:53 INFO automate.yml saved
Traceback (most recent call last):
  File "/Users/kashfifahim/Desktop/cupdate/opt/crosscompute/crosscompute/scripts/launch.py", line 92, in get_automation_from
    automation = DiskAutomation.load(path_or_folder or '.')
  File "/Users/kashfifahim/Desktop/cupdate/opt/crosscompute/crosscompute/routines/automation.py", line 59, in load
    instance._initialize_from_folder(path_or_folder)
  File "/Users/kashfifahim/Desktop/cupdate/opt/crosscompute/crosscompute/routines/automation.py", line 90, in _initialize_from_folder
    raise CrossComputeConfigurationNotFoundError(
crosscompute.exceptions.CrossComputeConfigurationNotFoundError: configuration not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kashfifahim/Desktop/cupdate/bin/crosscompute", line 33, in <module>
    sys.exit(load_entry_point('crosscompute', 'console_scripts', 'crosscompute')())
  File "/Users/kashfifahim/Desktop/cupdate/opt/crosscompute/crosscompute/scripts/launch.py", line 40, in do
    automation = get_automation_from(args)
  File "/Users/kashfifahim/Desktop/cupdate/opt/crosscompute/crosscompute/scripts/launch.py", line 97, in get_automation_from
    automation = DiskAutomation.load(path)
  File "/Users/kashfifahim/Desktop/cupdate/opt/crosscompute/crosscompute/routines/automation.py", line 61, in load
    instance._initialize_from_path(path_or_folder)
  File "/Users/kashfifahim/Desktop/cupdate/opt/crosscompute/crosscompute/routines/automation.py", line 99, in _initialize_from_path
    self._file_code_by_path = self._get_file_code_by_path()
  File "/Users/kashfifahim/Desktop/cupdate/opt/crosscompute/crosscompute/routines/automation.py", line 234, in _get_file_code_by_path
    packs.extend(zip(self._get_template_paths(), repeat('t')))
  File "/Users/kashfifahim/Desktop/cupdate/opt/crosscompute/crosscompute/routines/automation.py", line 275, in _get_template_paths
    d = automation_definition.template_path_by_id
UnboundLocalError: local variable 'automation_definition' referenced before assignment
```
Context: After setting up my script, I ran the command crosscompute on its own. The CLI helped set up the auomate.yml file.  After saving the file, the error was raised.

**Comment by invisibleroads** [comment]
We re-tested the configuration and this error does not appear in the latest commit.
