### ISSUE TITLE
crosscompute.exceptions.CrossComputeConfigurationError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by kashfifahim** [crosscompute/crosscompute#54]
Context: 
Using MacOSX 12.2.1, Python3.9

Running virtual environment, ```automation```, with the latest version of crosscompute, 0.9.1.2, installed ```via pip install crosscompute```. This error came up when I entered the command ```crosscompute```, by itself, I was hoping to get the cli prompts to fill in the first couple of fields for the automate.yml file.

```(automation) kashfifahim@crosscompute Bikeshare % crosscompute 
2022-02-28 17:52:38 INFO existing configuration not found; configuring new automation

Traceback (most recent call last):
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/scripts/launch.py", line 92, in get_automation_from
    automation = DiskAutomation.load(path_or_folder or '.')
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/routines/automation.py", line 60, in load
    instance._initialize_from_folder(path_or_folder)
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/routines/automation.py", line 91, in _initialize_from_folder
    raise CrossComputeConfigurationNotFoundError(
crosscompute.exceptions.CrossComputeConfigurationNotFoundError: configuration not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/routines/configuration.py", line 238, in load_raw_configuration_yaml
    with open(configuration_path, 'rt') as configuration_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/templates/configuration.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kashfifahim/Desktop/automation/bin/crosscompute", line 8, in <module>
    sys.exit(do())
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/scripts/launch.py", line 40, in do
    automation = get_automation_from(args)
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/scripts/launch.py", line 96, in get_automation_from
    path = configure_with(args)
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/scripts/configure.py", line 40, in configure_with
    return configure(args.path_or_folder)
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/scripts/configure.py", line 52, in configure
    configuration, configuration_path = input_configuration(
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/scripts/configure.py", line 61, in input_configuration
    configuration = load_raw_configuration(
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/routines/configuration.py", line 212, in load_raw_configuration
    return load_raw_configuration(configuration_path, with_comments)
  File "/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/routines/configuration.py", line 241, in load_raw_configuration_yaml
    raise CrossComputeConfigurationError(e)
crosscompute.exceptions.CrossComputeConfigurationError: [Errno 2] No such file or directory: '/Users/kashfifahim/Desktop/automation/lib/python3.9/site-packages/crosscompute/templates/configuration.yaml'```

**Comment by invisibleroads** [comment]
Oh great find!

**Comment by kashfifahim** [comment]
Works.  I also like that the .yml file comes with all the boiler plate code commented out; that's much appreciated!
