### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kashfifahim** [crosscompute/crosscompute#57]
While prototyping for Conference Calendar tool, I encountered a bug.  

Context:
In my script I am saving a sorted dataframe as a .csv file to an output_folder.

In my automate.yml file, I have configured the output section with a variable, id, and path.
I also configured the script section.

The framework deploys, creating the first view with the title and a link to the tool. Once you click the tool, I get the following error message on the browser and the error messages in the terminal:

```
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```

```bash 
(crosscomputeframework) kashfifahim@crosscompute ConferenceCalendar % crosscompute automate.yml
2022-05-31 17:27:26 INFO serving at http://127.0.0.1:7000
2022-05-31 17:27:56 ERROR Exception while serving /a/conference-calendar
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/view.py", line 786, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/waitress/channel.py", line 397, in service
    task.service()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/router.py", line 245, in invoke_request
    response = handle_request(request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
    result = view(context, request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/viewderivers.py", line 92, in mapped_view
    return _mapped_view(context, request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyramid/viewderivers.py", line 141, in _requestonly_view
    response = view(request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/crosscompute/routes/automation.py", line 195, in see_automation
    automation_definition.batch_definitions[0],
IndexError: list index out of range
```

**Comment by invisibleroads** [comment]
It looks like you don't have any batch definitions defined. I will make the
error message better handled so that it's nota scary traceback
